### ISSUE TITLE
Invalid Files on Yu-RIS VN, after deleting them, the scripts extract weirdly

### ISSUE THREAD

**Issue by SGifto73** [arcusmaximus/VNTranslationTools#121]
I'm trying to extract a Yu-RIS VN (https://vndb.org/v5928) and I already got all of the .ybn files unpacked from the .ypf using GARbro, but when I attempt to extract the files using VNTextPatch, I get some invalid files, namely yst00075 and yst00108 through yst00127.
![image](https://user-images.githubusercontent.com/125715965/219829750-6a6b3ec8-e0a4-4a56-a550-85f654d77035.png)

After this, I thought to give it another go after deleting the invalid data as described in another issue from earlier, after eliminating all of the invalid data I was left with a few files that just seemed to describe system components, like the "are you sure you want to end the game" message and a few names.
![image](https://user-images.githubusercontent.com/125715965/219829838-5208ddbe-f38f-4633-9344-c33792f5ff4b.png)
Here's the files  I end up with after the weird extraction:
![image](https://user-images.githubusercontent.com/125715965/219829877-136b1528-af22-412b-b920-b4d00a05aa0d.png)

I'm sorry if it's an obvious error or something, I'm new to this.

I attached the ysbin folder below with all files:
[ysbin.zip](https://github.com/arcusmaximus/VNTranslationTools/files/10773001/ysbin.zip)

Below is another download with the invalid data files removed:
[ysbinRemoved.zip](https://github.com/arcusmaximus/VNTranslationTools/files/10773003/ysbinRemoved.zip)

**Comment by arcusmaximus** [comment]
yst00075 looks to be actually invalid, but the others failed due to a bug in VNTextPatch. Fixed now.

**Comment by SGifto73** [comment]
![image](https://user-images.githubusercontent.com/125715965/219966579-4058fdd5-39ae-4bd4-8261-9d40b4e688cd.png)
Sorry to bug you again but I'm actually still getting this error on 108 and onwards.

**Comment by arcusmaximus** [comment]
Must've accidentally unchecked the file in question before committing... Try now.

**Comment by SGifto73** [comment]
![image](https://user-images.githubusercontent.com/125715965/219968494-1048db29-024e-459d-80c0-593cbfc5cd20.png)
So it worked, but it seems like it pulled several lines into one? I was able to extract the scripts manually after a lot of effort (I still ideally would like to use this tool since the formatting is really nice lol), and it seems like it's consolidating several lines into one block on the spreadsheet.

**Comment by arcusmaximus** [comment]
Fixed.
